DO $$
DECLARE
    terrains TEXT[] := ARRAY[
        'forest','grassland','beach','sea','roughland','urban',
        'ocean','snow','desert','mountain','volcanic','swamp'
    ];

    v_user_qwe_id   INT;
    v_user_ar_id    INT;
    v_user_dm_id    INT;
    v_user_admin_id INT;
    v_user_p5_id    INT;

    v_map_id   INT;
    v_map_name VARCHAR(100);
    v_map_w    INT;
    v_map_h    INT;

    v_tile_id  INT;
    v_terrain  VARCHAR(50);

    poi_count  INT;
    evt_count  INT;
BEGIN
    PERFORM setseed(0.1337);

    TRUNCATE t_events, t_points_of_interest, t_tiles, t_maps, t_exercise, t_roles, t_users
    RESTART IDENTITY CASCADE;

    INSERT INTO t_roles (code, is_default) VALUES
      ('ROLE_adm', FALSE),
      ('ROLE_pc',  TRUE),
      ('ROLE_dm',  FALSE);

    INSERT INTO t_users (email, password, username) VALUES
      ('qwe@qwe.com',        '$2a$14$c4MHAPI97tCGi04Xu/7FkOPdZB6il1j/bb6/gZGuWIUdVV8k541Ge', 'QweUser'),
      ('arabic@fakemail.com','$2a$14$8.spqi.bKBGRd11KCBwFyeV3FA9KvE/fRwnaAMUCQi1OCSpqFzRhW', 'مستخدم'),
      ('dungeon@master.com', '$2a$14$zlvjoEo3SEE515lXUlSw0OSMAejP4q1GZSZiiCnmH9G.JKM8TgFhu', 'DungeonMaster'),
      ('admin@moot.com',     '$2a$14$/AfJS0431a7kwKYgW5y8HOD2lMeK6Fs5UJeoO1pll0DkLUVCNuchu', 'AdminUser'),
      ('player5@game.com',   '$2a$14$.zVnb2QKt2l5/H/kuLibSOdeGSXYkxzsmczTRFVtlxjo2s8pDATmm', 'PlayerFive');

    SELECT id INTO v_user_qwe_id   FROM t_users WHERE email = 'qwe@qwe.com';
    SELECT id INTO v_user_ar_id    FROM t_users WHERE email = 'arabic@fakemail.com';
    SELECT id INTO v_user_dm_id    FROM t_users WHERE email = 'dungeon@master.com';
    SELECT id INTO v_user_admin_id FROM t_users WHERE email = 'admin@moot.com';
    SELECT id INTO v_user_p5_id    FROM t_users WHERE email = 'player5@game.com';

    INSERT INTO t_exercise (user_id, role_id)
    SELECT u.id, r.id
    FROM t_users u
    JOIN t_roles r
      ON ( (u.email = 'admin@moot.com' AND r.code = 'ROLE_adm')
        OR (u.email = 'dungeon@master.com' AND r.code = 'ROLE_dm')
        OR (u.email NOT IN ('admin@moot.com','dungeon@master.com') AND r.code = 'ROLE_pc') );


    INSERT INTO t_maps (user_id, name, width, height) VALUES
      (v_user_qwe_id, 'Qwe Tiny 2x2',    2,   2),
      (v_user_qwe_id, 'Qwe Wide 20x3',  20,   3),
      (v_user_qwe_id, 'Qwe Tall 1x100',  1, 100),
      (v_user_qwe_id, 'Qwe Big 25x25', 25,  25);

    INSERT INTO t_maps (user_id, name, width, height)
    SELECT id, 'Map A 5x5', 5, 5 FROM t_users WHERE email <> 'qwe@qwe.com';
    INSERT INTO t_maps (user_id, name, width, height)
    SELECT id, 'Map B 5x5', 5, 5 FROM t_users WHERE email <> 'qwe@qwe.com';

    FOR v_map_id, v_map_name, v_map_w, v_map_h IN
        SELECT id, name, width, height FROM t_maps
    LOOP
        FOR v_y IN 0..(v_map_h - 1) LOOP
            FOR v_x IN 0..(v_map_w - 1) LOOP
                v_terrain := terrains[1 + floor(random() * array_length(terrains, 1))::int];

                INSERT INTO t_tiles (map_id, x, y, terrain, description)
                VALUES (
                    v_map_id, v_x, v_y, v_terrain,
                    format('Tile (%s,%s) of Map "%s" (ID %s)', v_x, v_y, v_map_name, v_map_id)
                )
                RETURNING id INTO v_tile_id;

                poi_count := floor(random() * 6)::int;

                FOR poi_i IN 1..poi_count LOOP
                	DECLARE v_poi_id INT; BEGIN
                    	INSERT INTO t_points_of_interest (tile_id, name, description)
                        VALUES (
                        	v_tile_id,
                        	format('poi %s of tile (%s,%s) %s of map %s',
                          		poi_i, v_x, v_y, v_terrain, v_map_name),
                           	format('Autogenerated POI %s for tile (%s,%s) on map %s',
                            	poi_i, v_x, v_y, v_map_name)
                        )
                       	RETURNING id INTO v_poi_id;

                        evt_count := floor(random() * 6)::int;
                           	FOR evt_i IN 1..evt_count LOOP
                               	INSERT INTO t_events (poi_id, name, description)
                            	VALUES (
                                 	v_poi_id,
                              	format('Event %s of POI %s', evt_i, poi_i),
                            	format('Autogenerated event %s for POI %s of tile (%s, %s) of map %s', 
									evt_i, poi_i, v_x, v_y, v_map_name)
                         	);
                    	END LOOP;
                	END;
             	END LOOP;
            END LOOP;
        END LOOP;
    END LOOP; 
END
$$ LANGUAGE plpgsql;
